pub mod day_01;
pub mod day_02;
pub mod day_03;
pub mod day_04;
pub mod day_05;
pub mod day_06;
pub mod day_07;
pub mod day_08;
pub mod day_09;
pub mod day_10;
pub mod day_11;
pub mod day_12;
pub mod day_13;
pub mod day_14;
pub mod day_15;
pub mod day_16;
pub mod day_17;
pub mod day_18;
pub mod day_19;
pub mod day_20;
pub mod day_21;
pub mod day_22;
pub mod day_23;
pub mod day_24;
pub mod day_25;
pub mod utils;
fn main() {
    // print!("Running Day 01: ");
    // utils::chrono(|| day_01::run());
    // print!("Running Day 02: ");
    // utils::chrono(|| day_02::run());
    // print!("Running Day 03: ");
    // utils::chrono(|| day_03::run());
    // print!("Running Day 04: ");
    // utils::chrono(|| day_04::run());
    // print!("Running Day 05: ");
    // utils::chrono(|| day_05::run());
    // print!("Running Day 06: ");
    // utils::chrono(|| day_06::run());
    // print!("Running Day 07: ");
    // utils::chrono(|| day_07::run());
    // print!("Running Day 08: ");
    // utils::chrono(|| day_08::run());
    // print!("Running Day 09: ");
    // utils::chrono(|| day_09::run());
    // print!("Running Day 10: ");
    // utils::chrono(|| day_10::run());
    // print!("Running Day 11: ");
    // utils::chrono(|| day_11::run());
    // print!("Running Day 12: ");
    // utils::chrono(|| day_12::run());
    print!("Running Day 13: ");
    utils::chrono(|| day_13::run());
    // print!("Running Day 14: ");
    // utils::chrono(|| day_14::run());
    // print!("Running Day 15: ");
    // utils::chrono(|| day_15::run());
    // print!("Running Day 16: ");
    // utils::chrono(|| day_16::run());
    // print!("Running Day 17: ");
    // utils::chrono(|| day_17::run());
    // print!("Running Day 18: ");
    // utils::chrono(|| day_18::run());
    // print!("Running Day 19: ");
    // utils::chrono(|| day_19::run());
    // print!("Running Day 20: ");
    // utils::chrono(|| day_20::run());
    // print!("Running Day 21: ");
    // utils::chrono(|| day_21::run());
    // print!("Running Day 22: ");
    // utils::chrono(|| day_22::run());
    // print!("Running Day 23: ");
    // utils::chrono(|| day_23::run());
    // print!("Running Day 24: ");
    // utils::chrono(|| day_24::run());
    // print!("Running Day 25: ");
    // utils::chrono(|| day_25::run());
}    